<div class="login_wrapper">
    <div class="animate form login_form">
        <section class="login_content">
            <form>
                <h1>Install Dockent</h1>
                <div>
                    <input type="text" class="form-control" placeholder="Host" required="" />
                </div>
                <div>
                    <input type="text" class="form-control" placeholder="Path for the client certificates" required="" />
                </div>
                <div>
                    <input type="text" class="form-control" placeholder="Peer name of the docker daemon" required="" />
                </div>

                <div>
                    <a class="btn btn-default submit" href="index.html">Install</a>
                </div>

                <div class="clearfix"></div>

                <div class="separator">
                    <div class="clearfix"></div>
                    <br />

                    <div>
                        <p>©2016 All Rights Reserved. Dockent</p>
                    </div>
                </div>
            </form>
        </section>
    </div>
</div>