<?php
/**
 * @var \Phalcon\Mvc\View $this
 */
?>


<div class="login_wrapper">
    <div class="animate form login_form">
        <section class="login_content">
            <form method="post">
                <h1>Install Dockent</h1>
                <div>
                    <input type="text" class="form-control" placeholder="Remote socket" name="remote_socket" required="" />
                </div>
                <div>
                    <input type="checkbox" class="" placeholder="Use SSL" id="sslChk" name="ssl" required="" />
                    <label for="sslChk">Use SSL</label>
                </div>

                <div>
                    <a class="btn btn-default submit" href="index.html">Install</a>
                </div>

                <div class="clearfix"></div>

                <div class="separator">
                    <div class="clearfix"></div>
                    <br />

                    <div>
                        <p>©<?= date('Y') ?> All Rights Reserved. Dockent</p>
                    </div>
                </div>
            </form>
        </section>
    </div>
</div>