build:
  nodes:
    analysis:
      dependencies:
        before:
          - sudo apt-get update && apt-get install libyaml-dev
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
          -
            command: phpcs-run
            use_website_config: true
    tests: true
filter:
  excluded_paths:
    - 'tests/*'
checks:
  php: true
coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
      other:
        after_type_cast: false
