build:
  nodes:
    analysis:
      dependencies:
        before:
          - sudo apt-get -y install libyaml-dev
          - yes | pecl install psr
        override:
          - curl -s https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh | sudo bash
          - sudo apt-get install php7.2-phalcon
          - yes | pecl install yaml
          - composer install --no-interaction
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
          -
            command: phpcs-run
            use_website_config: true
    tests:
      dependencies:
        before:
          - sudo apt-get -y install libyaml-dev
          - yes | pecl install psr
        override:
          - curl -s https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh | sudo bash
          - sudo apt-get install php7.2-phalcon
          - yes | pecl install yaml
          - composer install --no-interaction
filter:
  excluded_paths:
    - 'tests/*'
checks:
  php: true
coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
      other:
        after_type_cast: false
