image: mileschou/phalcon

pipelines:
  branches:
    master:
      - step:
          caches:
            - composer
          script:
            - apt-get update && apt-get install -y unzip git zlib1g-dev libicu-dev libyaml-dev wget
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - docker-php-ext-install intl
            - docker-php-ext-install zip
            - cd /usr/src/php/ext && wget https://pecl.php.net/get/yaml-2.0.2.tgz && tar -xvf yaml-2.0.2.tgz && rm yaml-2.0.2.tgz && mv yaml-2.0.2 yaml
            - docker-php-ext-install yaml
            - composer install
            - composer test