<?php
/**
 * @var \Docker\API\Model\ImageItem[] $images
 */
?>

<!-- page content -->
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Images</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <form action="#" method="post" id="bulk-form">
                        <div class="row">
                            <div class="btn-group">
                                <a class="btn btn-default" onclick="submit('remove')">
                                    <i class="fa fa-trash" aria-hidden="true"></i> Remove
                                </a>
                            </div>
                        </div>
                    <table class="table">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Repository</th>
                            <th>Image ID</th>
                            <th>Created</th>
                            <th>Size</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($images as $image) : ?>
                            <?php foreach ($image->getRepoTags() as $tag) : ?>
                            <tr>
                                <td><input type="checkbox" name="id[]" value="<?= $tag ?>"></td>
                                <td><?= $tag ?></td>
                                <td><?= $image->getId() ?></td>
                                <td><?= date(DateTime::COOKIE, $image->getCreated()) ?></td>
                                <td><?= $image->getSize() ?></td>
                                <td>
                                    <div class="btn-group">
                                        <a href="/image/remove/<?= $tag ?>"
                                           class="btn btn-default btn-xs">
                                            <i class="fa fa-trash" aria-hidden="true"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>
<!-- /page content -->

<script>
    function submit(action) {
        var form = document.getElementById('bulk-form');
        form.setAttribute('action', '/image/bulk/' + action);
        form.submit();
    }
</script>