<?php
/**
 * Created by PhpStorm.
 * User: vpozdnyakov
 * Date: 28.11.17
 * Time: 17:34
 *
 * @var \Dockent\models\CreateNetwork $model
 */

use Dockent\components\RenderInputs;

?>


<div class="x_title">
    <h2>Creating the network</h2>
    <div class="clearfix"></div>
</div>
<div class="x_content">
    <br/>
    <form method="post" action="/network/create" class="form-horizontal form-label-left">

        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name-input">Name <span
                        class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?= RenderInputs::inputText($model->getName(), $model->getError('Name'), [
                    'name' => 'Name',
                    'required' => true
                ]) ?>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="driver-input">Driver</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?= RenderInputs::inputText($model->getDriver(), $model->getError('Driver'), [
                    'name' => 'Driver',
                    'placeholder' => 'bridge'
                ]) ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?= RenderInputs::inputCheckbox($model->isCheckDuplicate(), 'Check duplicate',
                    $model->getError('CheckDuplicate'), [
                        'name' => 'CheckDuplicate'
                    ]) ?>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?= RenderInputs::inputCheckbox($model->isInternal(), 'Internal',
                    $model->getError('Internal'), [
                        'name' => 'Internal'
                    ]) ?>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?= RenderInputs::inputCheckbox($model->isAttachable(), 'Attachable',
                    $model->getError('Attachable'), [
                        'name' => 'Attachable'
                    ]) ?>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?= RenderInputs::inputCheckbox($model->isIngress(), 'Ingress', $model->getError('Ingress'), [
                    'name' => 'Ingress'
                ]) ?>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?= RenderInputs::inputCheckbox($model->isEnableIPv6(), 'Enable IPv6',
                    $model->getError('EnableIPv6'), [
                        'name' => 'EnableIPv6'
                    ]) ?>
            </div>
        </div>

        <div class="ln_solid"></div>
        <div class="form-group">
            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <a href="/network/" class="btn btn-primary" type="button">Cancel</a>
                <button class="btn btn-primary" type="reset">Reset</button>
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>

    </form>
</div>
<!-- /page content -->
