<?php
/**
 * @var stdClass[] $networks
 */
?>


<div class="x_title">
    <h2>Network</h2>
    <div class="clearfix"></div>
</div>
<div class="x_content">
    <form action="#" method="post" id="bulk-form">
        <div class="row">
            <div class="btn-group">
                <a class="btn btn-default" onclick="submit('remove')">
                    <i class="fa fa-trash" aria-hidden="true"></i> Remove
                </a>
            </div>
        </div>
        <table class="table">
            <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Id</th>
                <th>Created</th>
                <th>Scope</th>
                <th>Driver</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($networks as $network) : ?>
                <tr>
                    <td><input type="checkbox" name="id[]" value="<?= $network->Id ?>"></td>
                    <td>
                        <a href="/network/view/<?= $network->Id ?>"><?= $network->Name ?></a>
                    </td>
                    <td>
                        <a href="/network/view/<?= $network->Id ?>"><?= $network->Id ?></a>
                    </td>
                    <td><?= $network->Created ?></td>
                    <td><?= $network->Scope ?></td>
                    <td><?= $network->Driver ?></td>
                    <td>
                        <div class="btn-group">
                            <a href="/network/remove/<?= $network->Id ?>"
                               class="btn btn-default btn-xs">
                                <i class="fa fa-trash" aria-hidden="true"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </form>
</div>

<!-- /page content -->

<script>
    function submit(action) {
        var form = document.getElementById('bulk-form');
        form.setAttribute('action', '/network/bulk/' + action);
        form.submit();
    }
</script>