<?php
/**
 * Created by PhpStorm.
 * User: vladyslavpozdnyakov
 * @var stdClass $model
 */
?>

<div class="" role="tabpanel" data-example-id="togglable-tabs">
    <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
        <li role="presentation" class="active"><a href="#network_inspect" id="network-inspect-tab" role="tab"
                                                  data-toggle="tab" aria-expanded="true">Network inspect</a>
        </li>
        <li role="presentation" class=""><a href="#containers" role="tab" id="containers-tab"
                                            data-toggle="tab" aria-expanded="false">Containers</a>
        </li>
    </ul>
    <div id="myTabContent" class="tab-content">
        <div role="tabpanel" class="tab-pane fade active in" id="network_inspect"
             aria-labelledby="network-inspect-tab">
            <div class="x_content">
                <div class="table-responsive">
                    <table class="table">
                        <tbody>
                        <tr>
                            <th>Name</th>
                            <td><?= $model->Name ?></td>
                        </tr>
                        <tr>
                            <th>Id</th>
                            <td><?= $model->Id ?></td>
                        </tr>
                        <tr>
                            <th>Created</th>
                            <td><?= $model->Created ?></td>
                        </tr>
                        <tr>
                            <th>Scope</th>
                            <td><?= $model->Scope ?></td>
                        </tr>
                        <tr>
                            <th>Driver</th>
                            <td><?= $model->Driver ?></td>
                        </tr>
                        <tr>
                            <th>Enable IPv6</th>
                            <td><i class="fa fa<?= $model->EnableIPv6 ? '-check' : '' ?>-square-o"
                                   aria-hidden="true"></i></td>
                        </tr>
                        <tr>
                            <th>Internal</th>
                            <td><i class="fa fa<?= $model->Internal ? '-check' : '' ?>-square-o"
                                   aria-hidden="true"></i></td>
                        </tr>
                        <tr>
                            <th>Attachable</th>
                            <td><i class="fa fa<?= $model->Attachable ? '-check' : '' ?>-square-o"
                                   aria-hidden="true"></i></td>
                        </tr>
                        <tr>
                            <th>Ingress</th>
                            <td><i class="fa fa<?= $model->Ingress ? '-check' : '' ?>-square-o"
                                   aria-hidden="true"></i></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div role="tabpanel" class="tab-pane fade" id="containers" aria-labelledby="containers-tab">
            <div class="x_content">
                <table class="table">
                    <thead>
                    <tr>
                        <th> Name</th>
                        <th> Endpoint Id</th>
                        <th> MAC address</th>
                        <th> IPv4 address</th>
                        <th> IPv6 address</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($model->Containers as $container) : ?>
                        <tr>
                            <td><a href="/container/view/<?= $container->Name ?>"><?= $container->Name ?></a></td>
                            <td><a href="/container/view/<?= $container->Name ?>"><?= $container->EndpointID ?></a></td>
                            <td><?= $container->MacAddress ?></td>
                            <td><?= $container->IPv4Address ?></td>
                            <td><?= $container->IPv6Address ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->