<?php
/**
 * Created by PhpStorm.
 * User: vpozdnyakov
 * Date: 26.09.17
 * Time: 10:59
 *
 * @var \Dockent\models\CreateContainer $model
 */

use Dockent\components\RenderInputs;

?>


<div class="x_title">
    <h2>Creating the container</h2>
    <div class="clearfix"></div>
</div>
<div class="x_content">
    <br/>
    <form method="post" action="/container/create" class="form-horizontal form-label-left">

        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="image-input">Image <span
                        class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?= RenderInputs::inputText($model->getImage(), $model->getError('Image'), [
                    'name' => 'Image',
                    'placeholder' => 'ubuntu:latest',
                    'required' => true
                ]) ?>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="cmd-input">Cmd</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?= RenderInputs::inputText($model->getCmd(), $model->getError('Cmd'), [
                    'name' => 'Cmd',
                    'placeholder' => 'run.sh'
                ]) ?>
            </div>
        </div>
        <div class="form-group">
            <label for="name-input" class="control-label col-md-3 col-sm-3 col-xs-12">Name</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?= RenderInputs::inputText($model->getName(), $model->getError('Name'), [
                    'name' => 'Name',
                    'placeholder' => 'New container'
                ]) ?>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12">Options</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <input type="checkbox" id="start-checkbox" name="start"
                       class="flat" <?= $model->isStart() ? 'checked' : '' ?>/> Start after creating
            </div>
        </div>

        <div class="ln_solid"></div>
        <div class="form-group">
            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <a href="/container/" class="btn btn-primary" type="button">Cancel</a>
                <button class="btn btn-primary" type="reset">Reset</button>
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>

    </form>
</div>
<!-- /page content -->