<?php
/**
 * @var \Docker\API\Model\ContainerInfo[] $containers
 */

use Dockent\enums\ContainerState;

?>

<!-- page content -->
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Containers</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <form action="#" method="post" id="bulk-form">
                        <div class="row">
                            <div class="btn-group">
                                <a class="btn btn-default" onclick="submit('start')">
                                    <i class="fa fa-play" aria-hidden="true"></i> Start
                                </a>
                                <a class="btn btn-default" onclick="submit('restart')">
                                    <i class="fa fa-repeat" aria-hidden="true"></i> Restart
                                </a>
                                <a class="btn btn-default" onclick="submit('stop')">
                                    <i class="fa fa-stop" aria-hidden="true"></i> Stop
                                </a>
                                <a class="btn btn-default" onclick="submit('remove')">
                                    <i class="fa fa-trash" aria-hidden="true"></i> Remove
                                </a>
                            </div>
                        </div>
                        <table class="table">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Container ID</th>
                                <th>Name</th>
                                <th>Image</th>
                                <th>Ports</th>
                                <th>Created</th>
                                <th>Status</th>
                                <th>Command</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($containers as $container) : ?>
                                <tr>
                                    <td><input type="checkbox" name="id[]" value="<?= $container->getId() ?>"></td>
                                    <td>
                                        <i class="fa fa-circle <?= $container->getState() === ContainerState::RUNNING ? 'green' : 'red' ?>"></i>
                                        <?php if ($container->getState() === ContainerState::RUNNING) : ?>
                                            <a href="/container/view/<?= $container->getId() ?>"><?= substr($container->getId(), 0, 12) ?></a>
                                        <?php else: ?>
                                            <?= substr($container->getId(), 0, 12) ?>
                                        <?php endif; ?>
                                    </td>
                                    <td>
                                        <?php if ($container->getState() === ContainerState::RUNNING) : ?>
                                            <a href="/container/view/<?= $container->getId() ?>"><?= implode('; ', $container->getNames()) ?></a>
                                        <?php else: ?>
                                            <?= implode('; ', $container->getNames()) ?>
                                        <?php endif; ?>
                                    </td>
                                    <td><?= $container->getImage() ?></td>
                                    <td>
                                        <?php foreach ($container->getPorts() as $port) {
                                            echo $port->getPrivatePort() . ':' . $port->getPublicPort() . '<br>';
                                        } ?>
                                    </td>
                                    <td><?= date(DateTime::COOKIE, $container->getCreated()) ?></td>
                                    <td><?= $container->getStatus() ?></td>
                                    <td><?= $container->getCommand() ?></td>
                                    <td>
                                        <div class="btn-group">
                                            <a href="<?= $container->getCommand() ? '/container/start/' . $container->getId() : '#' ?>"
                                               class="btn btn-default btn-xs" <?= $container->getCommand() ? '' : 'disabled' ?>>
                                                <i class="fa fa-play" aria-hidden="true"></i>
                                            </a>
                                            <a href="<?= $container->getCommand() ? '/container/restart/' . $container->getId() : '#' ?>"
                                               class="btn btn-default btn-xs" <?= $container->getCommand() ? '' : 'disabled' ?>>
                                                <i class="fa fa-repeat" aria-hidden="true"></i>
                                            </a>
                                            <a href="/container/stop/<?= $container->getId() ?>"
                                               class="btn btn-default btn-xs">
                                                <i class="fa fa-stop" aria-hidden="true"></i>
                                            </a>
                                            <a href="/container/remove/<?= $container->getId() ?>"
                                               class="btn btn-default btn-xs">
                                                <i class="fa fa-trash" aria-hidden="true"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>
<!-- /page content -->

<script>
    function submit(action) {
        var form = document.getElementById('bulk-form');
        form.setAttribute('action', '/container/bulk/' + action);
        form.submit();
    }
</script>