<?php
/**
 * @var \Docker\API\Model\ContainerInfo[] $containers
 */
?>

<!-- page content -->
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Containers</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Container ID</th>
                            <th>Name</th>
                            <th>Image</th>
                            <th>Ports</th>
                            <th>Created</th>
                            <th>Status</th>
                            <th>Command</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($containers as $container) : ?>
                            <tr>
                                <td>
                                    <i class="fa fa-circle <?= $container->getState() === 'running' ? 'green' : 'red' ?>"></i>
                                    <?= substr($container->getId(), 0, 12) ?></td>
                                <td><?= implode('; ', $container->getNames()) ?></td>
                                <td><?= $container->getImage() ?></td>
                                <td>
                                    <?php foreach ($container->getPorts() as $port) {
                                        echo $port->getPrivatePort() . ':' . $port->getPublicPort() . '<br>';
                                    } ?>
                                </td>
                                <td><?= date(DateTime::COOKIE, $container->getCreated()) ?></td>
                                <td><?= $container->getStatus() ?></td>
                                <td><?= $container->getCommand() ?></td>
                                <td>
                                    <div class="btn-group">
                                        <a href="<?= $container->getCommand() ? '/container/start/' . $container->getId() : '#' ?>"
                                           class="btn btn-default btn-xs" <?= $container->getCommand() ? '' : 'disabled' ?>>
                                            <i class="fa fa-play" aria-hidden="true"></i>
                                        </a>
                                        <a href="<?= $container->getCommand() ? '/container/restart/' . $container->getId() : '#' ?>"
                                           class="btn btn-default btn-xs" <?= $container->getCommand() ? '' : 'disabled' ?>>
                                            <i class="fa fa-repeat" aria-hidden="true"></i>
                                        </a>
                                        <a href="/container/stop/<?= $container->getId() ?>"
                                           class="btn btn-default btn-xs">
                                            <i class="fa fa-stop" aria-hidden="true"></i>
                                        </a>
                                        <a href="/container/remove/<?= $container->getId() ?>"
                                           class="btn btn-default btn-xs">
                                            <i class="fa fa-trash" aria-hidden="true"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>

                </div>
            </div>
        </div>

    </div>
</div>
<!-- /page content -->