<?php
/**
 * Created by PhpStorm.
 * User: vladyslavpozdnyakov
 * Date: 09.10.2017
 * Time: 14:37
 *
 * @var stdClass $top
 */
?>

<div class="x_title">
    <h2> List process</h2>
    <div class="clearfix"></div>
</div>
<div class="x_content">

    <table class="table">
        <thead>
        <tr>
            <th> PID</th>
            <th> User</th>
            <th> Time</th>
            <th> Command</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($top->Processes as $process) : ?>
            <tr>
                <td><?= $process[0] ?></td>
                <td><?= $process[1] ?></td>
                <td><?= $process[2] ?></td>
                <td><?= $process[3] ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<!-- /page content -->