<?php
/**
 * Created by PhpStorm.
 * User: vladyslavpozdnyakov
 * Date: 09.10.2017
 * Time: 14:37
 *
 * @var stdClass $top
 * @var stdClass $model
 */
?>

<div class="" role="tabpanel" data-example-id="togglable-tabs">
    <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
        <li role="presentation" class="active"><a href="#container_inspect" id="container-inspect-tab" role="tab"
                                                  data-toggle="tab" aria-expanded="true">Container inspect</a>
        </li>
        <li role="presentation" class=""><a href="#network_settings" role="tab" id="network-settings-tab"
                                            data-toggle="tab" aria-expanded="false">Network settings</a>
        </li>
        <li role="presentation" class=""><a href="#configuration" role="tab" id="configuration-tab" data-toggle="tab"
                                            aria-expanded="false">Configuration</a>
        </li>
        <li role="presentation" class=""><a href="#state" role="tab" id="state-tab" data-toggle="tab"
                                            aria-expanded="false">State</a>
        </li>
        <li role="presentation" class=""><a href="#mounts" role="tab" id="mounts-tab" data-toggle="tab"
                                            aria-expanded="false">Mounts</a>
        </li>
        <?php if ($top !== null) : ?>
            <li role="presentation" class=""><a href="#list_processes" role="tab" id="list-processes-tab"
                                                data-toggle="tab"
                                                aria-expanded="false">List processes</a>
            </li>
        <?php endif; ?>
    </ul>
    <div id="myTabContent" class="tab-content">
        <div role="tabpanel" class="tab-pane fade active in" id="container_inspect"
             aria-labelledby="container-inspect-tab">
            <div class="x_content">
                <div class="table-responsive">
                    <table class="table">
                        <tbody>
                        <tr>
                            <th>App armor profile</th>
                            <td><?= $model->AppArmorProfile ?></td>
                        </tr>
                        <tr>
                            <th>Args</th>
                            <td><?= implode(' ', $model->Args) ?></td>
                        </tr>
                        <tr>
                            <th>Created</th>
                            <td><?= $model->Created ?></td>
                        </tr>
                        <tr>
                            <th>Driver</th>
                            <td><?= $model->Driver ?></td>
                        </tr>
                        <tr>
                            <th>Hostname Path</th>
                            <td><?= $model->HostnamePath ?></td>
                        </tr>
                        <tr>
                            <th>Hosts path</th>
                            <td><?= $model->HostsPath ?></td>
                        </tr>
                        <tr>
                            <th>Log Path</th>
                            <td><?= $model->LogPath ?></td>
                        </tr>
                        <tr>
                            <th>Id</th>
                            <td><?= $model->Id ?></td>
                        </tr>
                        <tr>
                            <th>Image</th>
                            <td><?= $model->Image ?></td>
                        </tr>
                        <tr>
                            <th>Mount label</th>
                            <td><?= $model->MountLabel ?></td>
                        </tr>
                        <tr>
                            <th>Name</th>
                            <td><?= $model->Name ?></td>
                        </tr>
                        <tr>
                            <th>Path</th>
                            <td><?= $model->Path ?></td>
                        </tr>
                        <tr>
                            <th>Process label</th>
                            <td><?= $model->ProcessLabel ?></td>
                        </tr>
                        <tr>
                            <th>Resolve config path</th>
                            <td><?= $model->ResolvConfPath ?></td>
                        </tr>
                        <tr>
                            <th>Restart count</th>
                            <td><?= $model->RestartCount ?></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div role="tabpanel" class="tab-pane fade" id="network_settings" aria-labelledby="network-settings-tab">
            <div class="x_content">
                <div class="table-responsive">
                    <table class="table">
                        <tbody>
                        <tr>
                            <th>Bridge</th>
                            <td><?= $model->NetworkSettings->Bridge ?></td>
                        </tr>
                        <tr>
                            <th>Sandbox Id</th>
                            <td><?= $model->NetworkSettings->SandboxID ?></td>
                        </tr>
                        <tr>
                            <th>Hairpin mode</th>
                            <td><?= $model->NetworkSettings->HairpinMode ?></td>
                        </tr>
                        <tr>
                            <th>Link local IPv6 address</th>
                            <td><?= $model->NetworkSettings->LinkLocalIPv6Address ?></td>
                        </tr>
                        <tr>
                            <th>Link local IPv6 prefix length</th>
                            <td><?= $model->NetworkSettings->LinkLocalIPv6PrefixLen ?></td>
                        </tr>
                        <tr>
                            <th>Sandbox key</th>
                            <td><?= $model->NetworkSettings->SandboxKey ?></td>
                        </tr>
                        <tr>
                            <th>Endpoint Id</th>
                            <td><?= $model->NetworkSettings->EndpointID ?></td>
                        </tr>
                        <tr>
                            <th>Gateway</th>
                            <td><?= $model->NetworkSettings->Gateway ?></td>
                        </tr>
                        <tr>
                            <th>Global IPv6 address</th>
                            <td><?= $model->NetworkSettings->GlobalIPv6Address ?></td>
                        </tr>
                        <tr>
                            <th>Global IPv6 prefix length</th>
                            <td><?= $model->NetworkSettings->GlobalIPv6PrefixLen ?></td>
                        </tr>
                        <tr>
                            <th>IP address</th>
                            <td><?= $model->NetworkSettings->IPAddress ?></td>
                        </tr>
                        <tr>
                            <th>IP prefix length</th>
                            <td><?= $model->NetworkSettings->IPPrefixLen ?></td>
                        </tr>
                        <tr>
                            <th>IPv6 gateway</th>
                            <td><?= $model->NetworkSettings->IPv6Gateway ?></td>
                        </tr>
                        <tr>
                            <th>MAC address</th>
                            <td><?= $model->NetworkSettings->MacAddress ?></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div role="tabpanel" class="tab-pane fade" id="configuration" aria-labelledby="configuration-tab">
            <div class="x_content">
                <div class="table-responsive">
                    <table class="table">
                        <tbody>
                        <tr>
                            <th>Attach Stderr</th>
                            <td><?= $model->Config->AttachStderr ?></td>
                        </tr>
                        <tr>
                            <th>Attach Stdin</th>
                            <td><?= $model->Config->AttachStdin ?></td>
                        </tr>
                        <tr>
                            <th>Attach Stdout</th>
                            <td><?= $model->Config->AttachStdout ?></td>
                        </tr>
                        <tr>
                            <th>Cmd</th>
                            <td><?= implode(' ', $model->Config->Cmd) ?></td>
                        </tr>
                        <tr>
                            <th>Domain name</th>
                            <td><?= $model->Config->Domainname ?></td>
                        </tr>
                        <tr>
                            <th>Env</th>
                            <td><?= implode(';', $model->Config->Env) ?></td>
                        </tr>
                        <tr>
                            <th>Hostname</th>
                            <td><?= $model->Config->Hostname ?></td>
                        </tr>
                        <tr>
                            <th>Image</th>
                            <td><?= $model->Config->Image ?></td>
                        </tr>
                        <tr>
                            <th>Open Stdin</th>
                            <td><?= $model->Config->OpenStdin ?></td>
                        </tr>
                        <tr>
                            <th>Stdin once</th>
                            <td><?= $model->Config->StdinOnce ?></td>
                        </tr>
                        <tr>
                            <th>Tty</th>
                            <td><?= $model->Config->Tty ?></td>
                        </tr>
                        <tr>
                            <th>User</th>
                            <td><?= $model->Config->User ?></td>
                        </tr>
                        <tr>
                            <th>Working directory</th>
                            <td><?= $model->Config->WorkingDir ?></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div role="tabpanel" class="tab-pane fade" id="state" aria-labelledby="state-tab">
            <div class="x_content">
                <div class="table-responsive">
                    <table class="table">
                        <tbody>
                        <tr>
                            <th>Error</th>
                            <td><?= $model->State->Error ?></td>
                        </tr>
                        <tr>
                            <th>Exit code</th>
                            <td><?= $model->State->ExitCode ?></td>
                        </tr>
                        <tr>
                            <th>Finished at</th>
                            <td><?= $model->State->FinishedAt ?></td>
                        </tr>
                        <tr>
                            <th>OOM killed</th>
                            <td><?= $model->State->OOMKilled ?></td>
                        </tr>
                        <tr>
                            <th>Dead</th>
                            <td><?= $model->State->Dead ?></td>
                        </tr>
                        <tr>
                            <th>Paused</th>
                            <td><?= $model->State->Paused ?></td>
                        </tr>
                        <tr>
                            <th>Pid</th>
                            <td><?= $model->State->Pid ?></td>
                        </tr>
                        <tr>
                            <th>Restarting</th>
                            <td><?= $model->State->Restarting ?></td>
                        </tr>
                        <tr>
                            <th>Running</th>
                            <td><?= $model->State->Running ?></td>
                        </tr>
                        <tr>
                            <th>Started at</th>
                            <td><?= $model->State->StartedAt ?></td>
                        </tr>
                        <tr>
                            <th>Status</th>
                            <td><?= $model->State->Status ?></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div role="tabpanel" class="tab-pane fade" id="mounts" aria-labelledby="mounts-tab">
            <div class="x_content">
                <table class="table">
                    <thead>
                    <tr>
                        <th> Name</th>
                        <th> Source</th>
                        <th> Destination</th>
                        <th> Driver</th>
                        <th> Mode</th>
                        <th> RW</th>
                        <th> Propagation</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($model->Mounts as $mount) : ?>
                        <tr>
                            <td><?= $mount->Name ?></td>
                            <td><?= $mount->Source ?></td>
                            <td><?= $mount->Destination ?></td>
                            <td><?= $mount->Driver ?></td>
                            <td><?= $mount->Mode ?></td>
                            <td><?= $mount->RW ?></td>
                            <td><?= $mount->Propagation ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
        <?php if ($top !== null) : ?>
            <div role="tabpanel" class="tab-pane fade" id="list_processes" aria-labelledby="list-processes-tab">
                <div class="x_content">
                    <table class="table">
                        <thead>
                        <tr>
                            <th> PID</th>
                            <th> User</th>
                            <th> Time</th>
                            <th> Command</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($top->Processes as $process) : ?>
                            <tr>
                                <td><?= $process[0] ?></td>
                                <td><?= $process[1] ?></td>
                                <td><?= $process[2] ?></td>
                                <td><?= $process[3] ?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
<!-- /page content -->