<?php
/**
 * @var \Dockent\models\Settings $config
 */

use Dockent\components\RenderInputs;

?>

<div class="x_title">
    <h2>Dockent Settings</h2>
    <div class="clearfix"></div>
</div>
<div class="x_content">
    <br/>
    <div class="alert alert-success alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
        </button>
        <strong>Be careful!</strong> Edit this settings only if you are sure of what are you doing <br>
        <strong>After save you need to restart next services</strong>: Dockent project, Dockent queue service
    </div>
    <form method="post" action="/settings" class="form-horizontal form-label-left">
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="queue-host-input">Beanstalkd
                Host <span
                        class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?= RenderInputs::inputText($config->getBeanstalkHost(), $config->getError('beanstalkHost'), [
                    'name' => 'beanstalkHost',
                    'required' => true
                ]) ?>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="queue-port-input">Beanstalkd
                Port <span
                        class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?= RenderInputs::inputText($config->getBeanstalkPort(), $config->getError('beanstalkPort'), [
                    'name' => 'beanstalkPort',
                    'required' => true
                ]) ?>
            </div>
        </div>

        <div class="ln_solid"></div>
        <div class="form-group">
            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <a href="/" class="btn btn-primary" type="button">Cancel</a>
                <button class="btn btn-primary" type="reset">Reset</button>
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>

    </form>
</div>
<!-- /page content -->