<div class="x_title">
    <h2>Dockerfile Builder</h2>
    <div class="clearfix"></div>
</div>
<div class="x_content">
    <br/>
    <form method="post" action="/builder" class="form-horizontal form-label-left">
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="from-input">From <span
                        class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <input type="text" id="from-input" name="from" required="required"
                       class="form-control col-md-7 col-xs-12" placeholder="ubuntu:latest">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="run-input">Run</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                                <textarea class="form-control" name="run" id="run-input" cols="30" rows="3"
                                          placeholder="apt-get update"></textarea>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="cmd-input">Cmd</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <input type="text" id="cmd-input" name="cmd"
                       class="form-control col-md-7 col-xs-12"
                       placeholder="[&quot;executable&quot;,&quot;param1&quot;,&quot;param2&quot;]">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="expose-input">Expose</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <input type="text" id="expose-input" name="expose"
                       class="form-control col-md-7 col-xs-12" placeholder="80">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="env-input">Env</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                                <textarea class="form-control" name="env" id="env-input" cols="30" rows="3"
                                          placeholder="<key> <value>"></textarea>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="add-input">Add</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                                <textarea class="form-control" name="add" id="add-input" cols="30" rows="3"
                                          placeholder="<src> <dest>"></textarea>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="copy-input">Copy</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                                <textarea class="form-control" name="copy" id="copy-input" cols="30"
                                          rows="3" placeholder="<src> <dest>"></textarea>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="volume-input">Volume</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <input type="text" id="volume-input" name="volume"
                       class="form-control col-md-7 col-xs-12" placeholder="/data,/data2">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="workdir-input">Workdir</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <input type="text" id="workdir-input" name="workdir"
                       class="form-control col-md-7 col-xs-12" placeholder="/path/to/workdir">
            </div>
        </div>

        <div class="ln_solid"></div>
        <div class="form-group">
            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <a href="/image/" class="btn btn-primary" type="button">Cancel</a>
                <button class="btn btn-primary" type="reset">Reset</button>
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>

    </form>
</div>
<!-- /page content -->