<?php
/**
 * @var \Dockent\models\DockerfileBuilder $model
 */

use Dockent\components\RenderInputs;

?>
<div class="x_title">
    <h2>Dockerfile Builder</h2>
    <div class="clearfix"></div>
</div>
<div class="x_content">
    <br/>
    <form method="post" action="/builder" class="form-horizontal form-label-left">
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="from-input">From <span
                        class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?= RenderInputs::inputText($model->getFrom(), $model->getError('from'), [
                    'name' => 'from',
                    'required' => true,
                    'placeholder' => 'ubuntu:latest'
                ]) ?>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="run-input">Run</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?= RenderInputs::inputTextarea($model->getRun(), $model->getError('run'), [
                    'name' => 'run',
                    'cols' => 30,
                    'rows' => 3,
                    'placeholder' => 'apt-get update'
                ]) ?>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="cmd-input">Cmd</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?= RenderInputs::inputText($model->getCmd(), $model->getError('cmd'), [
                    'name' => 'cmd',
                    'placeholder' => '[&quot;executable&quot;,&quot;param1&quot;,&quot;param2&quot;]'
                ]) ?>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="expose-input">Expose</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?= RenderInputs::inputText($model->getExpose(), $model->getError('expose'), [
                    'name' => 'expose',
                    'placeholder' => '80'
                ]) ?>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="env-input">Env</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?= RenderInputs::inputTextarea($model->getEnv(), $model->getError('env'), [
                    'name' => 'env',
                    'cols' => 30,
                    'rows' => 3,
                    'placeholder' => '<key> <value>'
                ]) ?>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="add-input">Add</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?= RenderInputs::inputTextarea($model->getAdd(), $model->getError('add'), [
                    'name' => 'add',
                    'cols' => 30,
                    'rows' => 3,
                    'placeholder' => '<src> <dest>'
                ]) ?>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="copy-input">Copy</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?= RenderInputs::inputTextarea($model->getCopy(), $model->getError('copy'), [
                    'name' => 'copy',
                    'cols' => 30,
                    'rows' => 3,
                    'placeholder' => '<src> <dest>'
                ]) ?>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="volume-input">Volume</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?= RenderInputs::inputText($model->getVolume(), $model->getError('volume'), [
                    'name' => 'volume',
                    'placeholder' => '/data,/data2'
                ]) ?>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="workdir-input">Workdir</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?= RenderInputs::inputText($model->getWorkdir(), $model->getError('workdir'), [
                    'name' => 'workdir',
                    'placeholder' => '/path/to/workdir'
                ]) ?>
            </div>
        </div>

        <div class="ln_solid"></div>
        <div class="form-group">
            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <a href="/image/" class="btn btn-primary" type="button">Cancel</a>
                <button class="btn btn-primary" type="reset">Reset</button>
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>

    </form>
</div>
<!-- /page content -->