<?php
/**
 * @var stdClass $assetManifest
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/<?= $assetManifest->{'main.css'} ?>">
    <title>Dockent</title>
</head>
<body>
<div id="root"></div>
<script type="text/javascript" src="/<?= $assetManifest->{'main.js'} ?>"></script>
</body>
</html>
